### ISSUE TITLE
Better measure for password strength

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/sakerhetskontrollen#14]
The current package that measures password strength has some problems.

1. It doesn't take anything other than character entropy into account. Effectively, `password`, one of the most common passwords, has an "okay" score...
2. The score between 0 (?) and 95 isn't very descriptive. Perhaps saying something like strength in relation to time is more useful. I don't know if there is a linear difference between 30 and 40 and 80 and 90 for example. Does 40 only take one year more than 30, and 90 a thousand more years than 80?
3. The package is not very popular and I'm not sure it is being audited. I think generally larger packages have more at stake if they are insecure or doing something shady (but of course the amount of downloads can't be the only factor taken into account when choosing a package).

I think we can choose this in the future, perhaps @Zigolox and @kelszo could recommend something?

**Comment by Zigolox** [comment]
I would say that [zxcvbn](https://github.com/dropbox/zxcvbn) from Dropbox is the best one to use. It gives a lot of facts such breaking time and what it considers weak.

**Comment by charlesmaddock** [comment]
@sakerhetspolisen has fixed this now, closing.
