### ISSUE TITLE
Bar button should be clickable

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/sakerhetskontrollen#15]
Right now you cannot press the buttons in the top bar. 
![image](https://user-images.githubusercontent.com/41542666/129023972-23a3b5ec-2683-448b-8afb-8d6543830704.png)
![image](https://user-images.githubusercontent.com/41542666/129024364-d8284679-4994-4e9d-ba14-cf5a0fca2db1.png)

**Comment by charlesmaddock** [comment]
Fixed!
