### ISSUE TITLE
Use sv for key name instead of swe

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/sakerhetskontrollen#17]
I think you should adhere to standards and use `sv` instead of `swe` as the key when using internationalization.

There are many places that you would need to replace that, particularly in `App.js`.

https://github.com/digitalungdom-se/sakerhetskontrollen/blob/ff2a6ced0504a4896b3b3c02ca30ceed7b78c0cb/src/App.js#L10-L32

Also, I think using "swe" may be causing you some bugs, such as not being able to switch back to Swedish.

**Comment by charlesmaddock** [comment]
Fixed
