### ISSUE TITLE
Use correct HTML element (button instead of div)

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/sakerhetskontrollen#18]
You should use the button element when creating a button, instead of a div element. There are many reasons and I don't think an long explanation from me will really help. Shortly, it helps the browser understand the contents of the page and makes it more accessible. Right now you can test for yourself between how many elements you can access with the tab key (the button isn't one of them).

If you are really pressed to use a div element, at least use the `role="button"` attribute, [see more information here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role).

https://github.com/digitalungdom-se/sakerhetskontrollen/blob/ff2a6ced0504a4896b3b3c02ca30ceed7b78c0cb/src/components/general/StyledButton.jsx#L29-L51

**Comment by charlesmaddock** [comment]
Fixed now, well spotted.
