### ISSUE TITLE
Change imports/exports to reduce bundle size

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/sakerhetskontrollen#22]
If you do something like this

```jsx
import { Dropdown } from "components/general"
```

you will actually import a bundle that includes everything else in the general directory. If you want to test this, you can use the above import statement and add a `console.log` statement in `Fade.jsx`.

When you import, you actually want to do it like this

```jsx
import Dropdown from "components/general/Dropdown"
```

You can read about a similar problem here:
https://nsisodiya.medium.com/reduce-size-in-ant-design-bundle-size-c35dad9ce3a8

**Comment by charlesmaddock** [comment]
Oh nice, didn't know this was the case. I'll make sure to fix this asap.
