### ISSUE TITLE
Förbättra resultat sida

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/sakerhetskontrollen#3]
Vad behöver förbättras?

Vilka funktioner vill vi ha?

**Comment by sakerhetspolisen** [comment]
- Det ska vara enklare att kunna dela sitt resultat, kanske genom att dela en badge på sociala medier? Typ ✨Säkerhetsexperten✨
- En snyggare animation mer än bara mätaren
- Mätaren måste bli mer stilren och passa quizdesignen

**Comment by Zigolox** [comment]
>     * Det ska vara enklare att kunna dela sitt resultat, kanske genom att dela en badge på sociala medier? Typ sparklesSäkerhetsexpertensparkles
> 
>     * En snyggare animation mer än bara mätaren
> 
>     * Mätaren måste bli mer stilren och passa quizdesignen

Mätaren snurrar också galet mycket när man fått poäng och visar på fel region 
![image](https://user-images.githubusercontent.com/41542666/127517681-4b4e8384-eade-44c1-adc7-c7e8c23c8375.png)

**Comment by charlesmaddock** [comment]
There is a new improved version now. I'll send a link in discord soon.
