### ISSUE TITLE
Confetti improvements

### ISSUE THREAD

**Issue by sakerhetspolisen** [digitalungdom-se/sakerhetskontrollen#30]
The confetti that is generated when the user answers correctly should originate from behind the header.

![Skärmavbild 2021-09-12 kl  11 25 49](https://user-images.githubusercontent.com/68159964/132982398-c894e656-1ca4-43b5-88e6-f74a5c981e31.png)

**Comment by sakerhetspolisen** [comment]
Another improvement is to even out the amount of confetti that is generated. The first time a user answers a question right, there is a lot of confetti. The second time, the confetti amount is a lot smaller.

**Comment by charlesmaddock** [comment]
Have made improvements to this now, closing
