### ISSUE TITLE
Snyggare, mer rewarding svarsida på frågor

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/sakerhetskontrollen#4]
Vad skulle snyggare svarsida se ut se ut som?

Vilka funktioner vill vi ha?

**Comment by sakerhetspolisen** [comment]
- Mer utrymme (text) för att informera testtagaren
- Animationer för rätt / fel
- Länk till SK kanske?

Bra inspiration: https://10ideesrecuesenuxdesign.castoretpollux.com

**Comment by charlesmaddock** [comment]
Improved now too.
