### ISSUE TITLE
Knappen "Gör obesvarade frågor" leder till obesvarade och frågor man svarade fel på

### ISSUE THREAD

**Issue by simonthor** [digitalungdom-se/sakerhetskontrollen#49]
Det kanske vore bättre att döpa om knappen till något i stil med "gör om frågor du fick fel på och testa andra frågor" men det är lite väl långt så något kortare är nog bättre. Länk till knapptexten: https://github.com/digitalungdom-se/sakerhetskontrollen/blob/a2052696503b9bd27e90e897250c3b20838dfa9f/src/translations/swe/common.json#L202

**Comment by charlesmaddock** [comment]
Väldigt sant, snyggt fångat. Vi ska inte ha denna funktion till MVP, men bra att fixa till framtiden. Tack!
