### ISSUE TITLE
Change text for share test

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/sakerhetskontrollen#65]
I think it would sound better if it's just called "Dela testet" instead of "Dela detta testet" since that it's implied that it is this test. The text for questions is however good.
![image](https://user-images.githubusercontent.com/41542666/138609792-8f69e4dc-1f49-43c0-b9b3-c6e80fc9bf63.png)

**Comment by charlesmaddock** [comment]
Fixed
