### ISSUE TITLE
/test och 404 sida

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/sakerhetskontrollen#9]
När man startar testet hamnar man under ["/test" ](sakerhetskontrollen.netlify.app/test) dock är detta ingen äkta sida så om man reloadar så kommer man bara till en 404 sida.

Det borde göra att man hamnar där man tidigare var. 
![image](https://user-images.githubusercontent.com/41542666/128353068-77d143c2-b921-48b7-be8f-af7f8e4cbda7.png)

**Comment by Nautman** [comment]
Can this be closed?

**Comment by Zigolox** [comment]
Maybe, depends on we think it's the intended behavior. Should we go back to the category selection window, the first site or the answered question. Right now it's the selection window

**Comment by charlesmaddock** [comment]
Think the selection window is good for now. I'll add a new issue for storing answer data so you can return to the point were you left soon though. Closing this for now.
